# Make the container form the docker file and a httpd container from the commands.txt

version: '3'
services:
  upload-server:
    image: purevert/upload-server
    build: .
    ports:
      - '8888:8888'
    volumes:
      - "./recieved:/home/node/app/recieved"

  apache-apaxy-server:
    image: apaxy
    build:
      context: ./apaxy-essentials/
      args:
        apaxyPath: ''
    ports:
      - '8080:8080' #host:container
    volumes:
      - './recieved/:/usr/local/apache2/htdocs/recieved'
