# Make the container form the docker file and a httpd container from the commands.txt

version: '3'
services:
  upload-server:
    image: purevert/upload-server
    build:
      context: .
      dockerfile: Dockerfile.upserv
    ports:
      - '8888:8888'
    volumes:
      - "./recieved:/home/node/app/recieved"

  apache-apaxy-server:
    image: apaxy-git
    build:
      context: .
      args:
        apaxyPath: ''
      dockerfile: Dockerfile.apaxy
    ports:
      - '8080:8080' #host:container
    volumes:
      - './recieved/:/usr/local/apache2/htdocs/recieved'
