# Make the container form the docker file and a httpd container from the commands.txt

version: '3'
services:
  upload-server:
    image: purevert/upload-server
    ports:
      - '8888:8888'
    volumes:
      - "./recieved:/home/node/app/recieved"
      
  apache-server:
    image: httpd:2.4
    ports:
      - '8080:80'
    volumes:
      - "./recieved:/usr/local/apache2/htdocs/"
