version: '3'
services:
  apaxy:
    image: apaxy
    build:
      context: .
      args:
        apaxyPath: ''
    ports:
      - '80:8080'
    volumes:
      - './share/:/usr/local/apache2/htdocs/share/'
